api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
        jsonhal: ['application/hal+json']
    docs_formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
#        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false

#    enable_docs: false
#    enable_entrypoint: false
#    enable_swagger: false
#    enable_swagger_ui: false
    swagger:
        api_keys:
            access_token:
                name: Authorization
                type: header

